/**
 * MCP Server for EDT
 * Copyright (C) 2025 DitriX (https://github.com/DitriXNew)
 * Licensed under AGPL-3.0-or-later
 */

package com.ditrix.edt.mcp.server.tools.impl;

import java.nio.file.Files;
import java.nio.file.InvalidPathException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicReference;

import org.eclipse.core.resources.IProject;
import org.eclipse.core.runtime.jobs.Job;

import com._1c.g5.v8.dt.platform.services.core.infobases.IInfobaseAssociationManager;
import com._1c.g5.v8.dt.platform.services.core.infobases.IInfobaseManager;
import com._1c.g5.v8.dt.platform.services.core.infobases.InfobaseAssociationSettings;
import com._1c.g5.v8.dt.platform.services.core.infobases.InfobaseReferences;
import com._1c.g5.v8.dt.platform.services.core.operations.IInfobaseCreationOperation;
import com._1c.g5.v8.dt.platform.services.model.InfobaseReference;
import com._1c.g5.v8.dt.platform.services.model.ModelFactory;
import com.ditrix.edt.mcp.server.Activator;
import com.ditrix.edt.mcp.server.protocol.JsonSchemaBuilder;
import com.ditrix.edt.mcp.server.protocol.JsonUtils;
import com.ditrix.edt.mcp.server.protocol.ToolResult;
import com.ditrix.edt.mcp.server.tools.IMcpTool;
import com.ditrix.edt.mcp.server.utils.ProjectContext;
import com.ditrix.edt.mcp.server.utils.ProjectStateChecker;
import com.e1c.g5.dt.applications.ApplicationException;
import com.e1c.g5.dt.applications.ApplicationUpdateState;
import com.e1c.g5.dt.applications.IApplication;
import com.e1c.g5.dt.applications.IApplicationManager;
import com.e1c.g5.dt.applications.infobases.IInfobaseApplication;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;

/**
 * Creates a new FILE infobase (1C:Enterprise database) and binds it to a configuration
 * project so it appears as an application in {@code get_applications}.
 *
 * <p>The operation decomposes into two distinct steps:
 * <ol>
 *   <li>Create the infobase on disk via {@code IInfobaseCreationOperation} (which shells out to
 *       the 1C thick client {@code 1cv8 CREATEINFOBASE}) — requires a registered 1C platform
 *       runtime. This step runs in a background Eclipse Job with a bounded timeout (120 s).</li>
 *   <li>Associate the infobase with the project via {@code IInfobaseAssociationManager.associate},
 *       which causes {@code InfobaseApplicationProvisionDelegate} to surface a new
 *       {@code IInfobaseApplication} of type {@code com.e1c.g5.dt.applications.type.infobase}.</li>
 * </ol>
 *
 * <p><strong>Unattended-safety:</strong> the create operation runs entirely in a background Job;
 * no SWT / UI-thread code is executed. A fast platform-availability probe fires before the Job
 * is submitted — if no 1C platform runtime is registered the tool fails immediately with an
 * actionable message instead of hanging.
 *
 * <p><strong>Scope: FILE infobases only.</strong> SERVER and WEB infobases require additional
 * DBMS / cluster parameters and are rejected with a clear "not yet supported" message.
 */
public class CreateInfobaseTool implements IMcpTool
{
    /** MCP tool name. */
    public static final String NAME = "create_infobase"; //$NON-NLS-1$

    /** Background-Job timeout for the actual infobase creation (1cv8 process). */
    private static final long CREATE_TIMEOUT_SECONDS = 120;

    /** Infobase application type ID as defined in the applications.infobases plugin.xml. */
    private static final String INFOBASE_APP_TYPE = "com.e1c.g5.dt.applications.type.infobase"; //$NON-NLS-1$

    @Override
    public String getName()
    {
        return NAME;
    }

    @Override
    public String getDescription()
    {
        return "Create a new FILE infobase (1C database) and bind it to a configuration project so " //$NON-NLS-1$
            + "it appears in get_applications. Requires a 1C platform runtime registered in EDT; " //$NON-NLS-1$
            + "FILE type only (server/web rejected). Runs in a background Job (up to 120 s). " //$NON-NLS-1$
            + "Full parameters and examples: call get_tool_guide('create_infobase')."; //$NON-NLS-1$
    }

    @Override
    public String getInputSchema()
    {
        return JsonSchemaBuilder.object()
            .stringProperty("projectName", //$NON-NLS-1$
                "EDT configuration project to bind the new infobase to (required).", true) //$NON-NLS-1$
            .stringProperty("infobaseFile", //$NON-NLS-1$
                "Absolute path to the directory where the infobase files (1Cv8.1CD) will be created " //$NON-NLS-1$
                + "(required). The directory must be writable; it will be created if it does not exist.", //$NON-NLS-1$
                true)
            .stringProperty("infobaseName", //$NON-NLS-1$
                "Display name for the new infobase. If omitted, a name is auto-generated by EDT.") //$NON-NLS-1$
            .stringProperty("platform", //$NON-NLS-1$
                "1C platform version mask to use for creation (e.g. '8.3.25'). If omitted, EDT " //$NON-NLS-1$
                + "resolves the best available installed version automatically.") //$NON-NLS-1$
            .booleanProperty("setDefault", //$NON-NLS-1$
                "Set the new infobase as the default application for the project after creation " //$NON-NLS-1$
                + "(default false).") //$NON-NLS-1$
            .build();
    }

    @Override
    public String getOutputSchema()
    {
        return JsonSchemaBuilder.object()
            .booleanProperty("success", "Whether the operation succeeded", true) //$NON-NLS-1$ //$NON-NLS-2$
            .stringProperty("action", "Always 'created' on success.") //$NON-NLS-1$ //$NON-NLS-2$
            .stringProperty("project", "Name of the configuration project.") //$NON-NLS-1$ //$NON-NLS-2$
            .stringProperty("infobaseFile", "Path of the created infobase directory.") //$NON-NLS-1$ //$NON-NLS-2$
            .stringProperty("infobaseName", "Display name of the created infobase.") //$NON-NLS-1$ //$NON-NLS-2$
            .objectArrayProperty("applications", //$NON-NLS-1$
                "Applications bound to the project after creation (same shape as get_applications).") //$NON-NLS-1$
            .stringProperty("applicationId", //$NON-NLS-1$
                "ID of the newly created infobase application (for chaining into update_database).") //$NON-NLS-1$
            .stringProperty("message", "Human-readable status message.") //$NON-NLS-1$ //$NON-NLS-2$
            .build();
    }

    @Override
    public ResponseType getResponseType()
    {
        return ResponseType.JSON;
    }

    @Override
    public String execute(Map<String, String> params)
    {
        // Required parameters
        String err = JsonUtils.requireArgument(params, "projectName"); //$NON-NLS-1$
        if (err != null)
        {
            return err;
        }
        String errFile = JsonUtils.requireArgument(params, "infobaseFile"); //$NON-NLS-1$
        if (errFile != null)
        {
            return errFile;
        }

        String projectName = JsonUtils.extractStringArgument(params, "projectName"); //$NON-NLS-1$
        String infobaseFileStr = JsonUtils.extractStringArgument(params, "infobaseFile"); //$NON-NLS-1$
        String infobaseName = JsonUtils.extractStringArgument(params, "infobaseName"); //$NON-NLS-1$
        String platform = JsonUtils.extractStringArgument(params, "platform"); //$NON-NLS-1$
        boolean setDefault = JsonUtils.extractBooleanArgument(params, "setDefault", false); //$NON-NLS-1$

        // Validate and normalize the infobase path early (before acquiring services)
        Path infobaseDir;
        try
        {
            infobaseDir = Paths.get(infobaseFileStr);
        }
        catch (InvalidPathException e)
        {
            return ToolResult.error("infobaseFile is not a valid path: '" + infobaseFileStr //$NON-NLS-1$
                + "': " + e.getMessage()).toJson(); //$NON-NLS-1$
        }

        // Refuse only the transient BUILDING state; missing/closed project falls through below.
        String building = ProjectStateChecker.buildingErrorOrNull(projectName);
        if (building != null)
        {
            return ToolResult.error(building).toJson();
        }

        return createInfobase(projectName, infobaseDir, infobaseName, platform, setDefault);
    }

    private String createInfobase(String projectName, Path infobaseDir,
            String infobaseName, String platform, boolean setDefault)
    {
        // --- 1. Resolve project ---
        ProjectContext ctx = ProjectContext.of(projectName);
        if (!ctx.exists())
        {
            return ToolResult.error(ProjectContext.notFoundMessage(projectName)).toJson();
        }
        if (!ctx.isOpen())
        {
            return ToolResult.error("Project is closed: " + projectName //$NON-NLS-1$
                + ". Open the project in EDT first.").toJson(); //$NON-NLS-1$
        }
        IProject project = ctx.project();

        // --- 2. Acquire services ---
        IApplicationManager appManager = Activator.getDefault().getApplicationManager();
        if (appManager == null)
        {
            return ToolResult.error("IApplicationManager service is not available").toJson(); //$NON-NLS-1$
        }

        IInfobaseManager ibManager = Activator.getDefault().getInfobaseManager();
        if (ibManager == null)
        {
            return ToolResult.error("IInfobaseManager service is not available. " //$NON-NLS-1$
                + "Ensure EDT platform-services are running.").toJson(); //$NON-NLS-1$
        }

        IInfobaseAssociationManager assocManager =
            Activator.getDefault().getInfobaseAssociationManager();
        if (assocManager == null)
        {
            return ToolResult.error("IInfobaseAssociationManager service is not available. " //$NON-NLS-1$
                + "Ensure EDT platform-services are running.").toJson(); //$NON-NLS-1$
        }

        // --- 3. Platform probe (CRITICAL unattended-safety gate) ---
        // IInfobaseCreationOperation shells out to 1cv8 which needs a registered platform runtime.
        // Probe BEFORE submitting the background Job so headless CI fails FAST and cleanly.
        IInfobaseCreationOperation creationOp = resolveCreationOperation();
        if (creationOp == null)
        {
            return ToolResult.error("No 1C platform runtime is registered in EDT - cannot create " //$NON-NLS-1$
                + "a new infobase. Register a 1C:Enterprise platform installation in EDT " //$NON-NLS-1$
                + "(Window -> Preferences -> 1C:Enterprise -> Installed Installations) " //$NON-NLS-1$
                + "and retry.").toJson(); //$NON-NLS-1$
        }

        // --- 4. Auto-generate infobase name if omitted ---
        if (infobaseName == null || infobaseName.isEmpty())
        {
            try
            {
                infobaseName = ibManager.generateInfobaseName();
            }
            catch (Exception e)
            {
                infobaseName = projectName + "_infobase"; //$NON-NLS-1$
            }
        }

        // --- 5. Ensure directory exists ---
        try
        {
            Files.createDirectories(infobaseDir);
        }
        catch (Exception e)
        {
            return ToolResult.error("Cannot create infobase directory '" + infobaseDir //$NON-NLS-1$
                + "': " + e.getMessage()).toJson(); //$NON-NLS-1$
        }

        // --- 6. Build the FILE infobase reference ---
        InfobaseReference ibRef =
            InfobaseReferences.newFileInfobaseReference(infobaseDir.toAbsolutePath().toString());
        ibRef.setName(infobaseName);

        // --- 7. Build the creation descriptor ---
        IInfobaseCreationOperation.Builder builder = new IInfobaseCreationOperation.Builder()
            .infobaseReference(ibRef)
            .createNew(true)
            .addReference(true)
            .arguments(ModelFactory.eINSTANCE.createCreateInfobaseArguments());
        if (platform != null && !platform.isEmpty())
        {
            builder.platform(platform);
        }
        final IInfobaseCreationOperation.Descriptor descriptor = builder.build();

        // --- 8. Run the creation in a background Job (bounded timeout) ---
        // NEVER call perform() on the UI thread and NEVER block indefinitely.
        final String finalInfobaseName = infobaseName;
        final IInfobaseCreationOperation finalOp = creationOp;
        final AtomicReference<Exception> jobError = new AtomicReference<>();

        Job createJob = new Job("Create infobase: " + finalInfobaseName) //$NON-NLS-1$
        {
            @Override
            protected org.eclipse.core.runtime.IStatus run(
                    org.eclipse.core.runtime.IProgressMonitor monitor)
            {
                try
                {
                    finalOp.perform(descriptor, monitor);
                }
                catch (Exception e)
                {
                    jobError.set(e);
                }
                return org.eclipse.core.runtime.Status.OK_STATUS;
            }
        };
        createJob.setUser(false);
        createJob.setSystem(true);
        createJob.schedule();

        try
        {
            boolean finished = createJob.join(
                TimeUnit.SECONDS.toMillis(CREATE_TIMEOUT_SECONDS), null);
            if (!finished)
            {
                createJob.cancel();
                return ToolResult.error("Infobase creation timed out after " //$NON-NLS-1$
                    + CREATE_TIMEOUT_SECONDS + " seconds. The 1cv8 process may still be running. " //$NON-NLS-1$
                    + "Check the EDT log and the target directory '" + infobaseDir //$NON-NLS-1$
                    + "' for partial results.").toJson(); //$NON-NLS-1$
            }
        }
        catch (InterruptedException e)
        {
            Thread.currentThread().interrupt();
            return ToolResult.error("Infobase creation was interrupted.").toJson(); //$NON-NLS-1$
        }

        if (jobError.get() != null)
        {
            Exception ex = jobError.get();
            Activator.logError("create_infobase: creation failed for " + infobaseDir, ex); //$NON-NLS-1$
            return ToolResult.error("Infobase creation failed: " + ex.getMessage() //$NON-NLS-1$
                + ". Verify that a compatible 1C platform is installed and that the " //$NON-NLS-1$
                + "target directory '" + infobaseDir + "' is accessible.").toJson(); //$NON-NLS-1$ //$NON-NLS-2$
        }

        Activator.logInfo("create_infobase: infobase created at " + infobaseDir); //$NON-NLS-1$

        // --- 9. Associate with the project ---
        try
        {
            assocManager.associate(project, ibRef, InfobaseAssociationSettings.notSynchronized());
        }
        catch (Exception e)
        {
            Activator.logError("create_infobase: association failed for project " + projectName, e); //$NON-NLS-1$
            return ToolResult.error("Infobase was created at '" + infobaseDir //$NON-NLS-1$
                + "' but could not be associated with project '" + projectName //$NON-NLS-1$
                + "': " + e.getMessage() //$NON-NLS-1$
                + ". Use delete_infobase to clean up if needed.").toJson(); //$NON-NLS-1$
        }

        Activator.logInfo("create_infobase: associated with project " + projectName); //$NON-NLS-1$

        // --- 10. Optionally set as default ---
        String setDefaultNote = null;
        if (setDefault)
        {
            try
            {
                IApplication newApp = findNewApplication(appManager, project, ibRef);
                if (newApp == null)
                {
                    setDefaultNote = "; the new infobase was created but could not be set as " //$NON-NLS-1$
                        + "default yet - set it manually or retry"; //$NON-NLS-1$
                    Activator.logError("create_infobase: setDefault skipped — new app not found yet", //$NON-NLS-1$
                        null);
                }
                else
                {
                    appManager.setDefaultApplication(project, newApp);
                }
            }
            catch (Exception e)
            {
                // Non-fatal: the infobase was created and associated; only the default-setting failed.
                Activator.logError("create_infobase: setDefault failed", e); //$NON-NLS-1$
            }
        }

        // --- 11. Read back and return ---
        return buildSuccessResult(projectName, infobaseDir, finalInfobaseName,
            appManager, project, ibRef, setDefaultNote);
    }

    /**
     * Attempts to resolve an {@link IInfobaseCreationOperation} instance from the
     * ps-core Guice injector via reflection.
     *
     * <p>This is the standard pattern for non-OSGi-service Guice prototype operations
     * (mirrors {@code EdtServices.getModelObjectFactory()} which does the same for the
     * MD language injector). Returns {@code null} if the platform-services plugin is
     * not loaded, if the injector is not available, or if the class is not bound — so
     * the caller can treat {@code null} as "platform not ready" and return an actionable
     * error without crashing.
     *
     * @return operation instance, or {@code null} when unavailable
     */
    private static IInfobaseCreationOperation resolveCreationOperation()
    {
        try
        {
            // com._1c.g5.v8.dt.internal.platform.services.core.PlatformServicesCore
            // (internal class — must be reached via reflection)
            Class<?> coreClass = Class.forName(
                "com._1c.g5.v8.dt.internal.platform.services.core.PlatformServicesCore"); //$NON-NLS-1$
            java.lang.reflect.Method getDefault = coreClass.getDeclaredMethod("getDefault"); //$NON-NLS-1$
            getDefault.setAccessible(true);
            Object coreInstance = getDefault.invoke(null);
            if (coreInstance == null)
            {
                return null;
            }
            java.lang.reflect.Method getInjector =
                coreClass.getDeclaredMethod("getInjector"); //$NON-NLS-1$
            getInjector.setAccessible(true);
            Object injector = getInjector.invoke(coreInstance);
            if (injector == null)
            {
                return null;
            }
            com.google.inject.Injector guiceInjector = (com.google.inject.Injector) injector;
            return guiceInjector.getInstance(IInfobaseCreationOperation.class);
        }
        catch (Exception e)
        {
            Activator.logError(
                "create_infobase: platform probe failed — PlatformServicesCore not available " //$NON-NLS-1$
                    + "(this is expected in headless CI without a 1C platform)", e); //$NON-NLS-1$
            return null;
        }
    }

    /**
     * Finds the newly created infobase application by matching the infobase reference.
     * Best-effort: returns {@code null} if not found.
     */
    private static IApplication findNewApplication(IApplicationManager appManager,
            IProject project, InfobaseReference ibRef)
    {
        try
        {
            Optional<IApplication> found =
                appManager.findApplicationByInfobaseAndProject(ibRef, project);
            return found.orElse(null);
        }
        catch (Exception e)
        {
            return null;
        }
    }

    /** Maximum re-poll attempts for the provision-delegate listener race after associate(). */
    private static final int READ_BACK_MAX_POLLS = 5;

    /** Delay between read-back re-poll attempts (ms). */
    private static final long READ_BACK_POLL_DELAY_MS = 300;

    /**
     * Reads back the applications for the project and builds the success JSON.
     * Uses a short bounded re-poll to handle the provision-delegate listener race
     * that can cause the new application to not yet appear immediately after associate().
     *
     * @param setDefaultNote optional note appended to the message when setDefault could not be
     *        completed (null = no note)
     */
    private static String buildSuccessResult(String projectName, Path infobaseDir,
            String infobaseName, IApplicationManager appManager,
            IProject project, InfobaseReference ibRef, String setDefaultNote)
    {
        JsonArray appsArray = new JsonArray();
        String newAppId = null;

        // Short bounded re-poll: the provision-delegate listener fires asynchronously after
        // associate(), so the new IInfobaseApplication may not be visible on the first read.
        for (int poll = 0; poll < READ_BACK_MAX_POLLS; poll++)
        {
            appsArray = new JsonArray();
            newAppId = null;

            try
            {
                List<IApplication> applications = appManager.getApplications(project);
                if (applications != null)
                {
                    for (IApplication app : applications)
                    {
                        JsonObject appObj = new JsonObject();
                        appObj.addProperty("id", app.getId()); //$NON-NLS-1$
                        appObj.addProperty("name", app.getName()); //$NON-NLS-1$
                        if (app.getType() != null)
                        {
                            appObj.addProperty("type", app.getType().getId()); //$NON-NLS-1$
                        }
                        try
                        {
                            ApplicationUpdateState updateState = appManager.getUpdateState(app);
                            if (updateState != null)
                            {
                                appObj.addProperty("updateState", updateState.name()); //$NON-NLS-1$
                            }
                        }
                        catch (ApplicationException e)
                        {
                            appObj.addProperty("updateState", "UNKNOWN"); //$NON-NLS-1$ //$NON-NLS-2$
                        }
                        // Identify the newly created application by matching the infobase reference.
                        if (newAppId == null
                            && app instanceof IInfobaseApplication
                            && INFOBASE_APP_TYPE.equals(
                                app.getType() != null ? app.getType().getId() : null))
                        {
                            IInfobaseApplication ibApp = (IInfobaseApplication) app;
                            if (ibApp.getInfobase() != null
                                && matchesRef(ibApp.getInfobase(), ibRef))
                            {
                                newAppId = app.getId();
                            }
                        }
                        appsArray.add(appObj);
                    }
                }
            }
            catch (ApplicationException e)
            {
                Activator.logError("create_infobase: error reading back applications", e); //$NON-NLS-1$
                break;
            }

            if (newAppId != null)
            {
                break; // Found the new application — no need to re-poll.
            }

            if (poll < READ_BACK_MAX_POLLS - 1)
            {
                try
                {
                    Thread.sleep(READ_BACK_POLL_DELAY_MS);
                }
                catch (InterruptedException ie)
                {
                    Thread.currentThread().interrupt();
                    break;
                }
            }
        }

        ToolResult result = ToolResult.success()
            .put("action", "created") //$NON-NLS-1$ //$NON-NLS-2$
            .put("project", projectName) //$NON-NLS-1$
            .put("infobaseFile", infobaseDir.toAbsolutePath().toString()) //$NON-NLS-1$
            .put("infobaseName", infobaseName) //$NON-NLS-1$
            .put("applications", appsArray); //$NON-NLS-1$

        if (newAppId != null)
        {
            result.put("applicationId", newAppId); //$NON-NLS-1$
        }

        String message = "Infobase '" + infobaseName //$NON-NLS-1$
            + "' created at '" + infobaseDir.toAbsolutePath() //$NON-NLS-1$
            + "' and bound to project '" + projectName //$NON-NLS-1$
            + "'. Use update_database to push the configuration into the infobase." //$NON-NLS-1$
            + (setDefaultNote != null ? setDefaultNote : ""); //$NON-NLS-1$
        result.put("message", message); //$NON-NLS-1$

        return result.toJson();
    }

    /**
     * Checks whether two infobase references point to the same FILE infobase by
     * comparing their connection-string file path. Best-effort: returns false on any
     * failure so a match-miss only skips the applicationId echo.
     */
    private static boolean matchesRef(InfobaseReference a, InfobaseReference b)
    {
        try
        {
            if (a.getConnectionString() == null || b.getConnectionString() == null)
            {
                return false;
            }
            String ca = a.getConnectionString().asConnectionString();
            String cb = b.getConnectionString().asConnectionString();
            return ca != null && ca.equalsIgnoreCase(cb);
        }
        catch (Exception e)
        {
            return false;
        }
    }
}
