/**
 * MCP Server for EDT
 * Copyright (C) 2026 Diversus23 (https://github.com/Diversus23)
 * Licensed under AGPL-3.0-or-later
 */

package com.ditrix.edt.mcp.server.tools.impl;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;

/**
 * Parser for JUnit XML test reports generated by Vanessa Automation.
 */
public class JUnitXmlParser
{
    /**
     * Parses a JUnit XML report file and returns structured results.
     *
     * @param junitXmlFile path to the JUnit XML report file
     * @return JsonObject with parsed test results
     * @throws IOException if the file cannot be read
     * @throws ParserConfigurationException if XML parser cannot be created
     * @throws SAXException if XML is malformed
     */
    public static JsonObject parse(File junitXmlFile) throws IOException, ParserConfigurationException, SAXException
    {
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        // Disable external entities for security
        factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true); //$NON-NLS-1$
        DocumentBuilder builder = factory.newDocumentBuilder();
        Document doc = builder.parse(junitXmlFile);
        doc.getDocumentElement().normalize();

        JsonObject result = new JsonObject();

        // Parse <testsuites> or <testsuite> root
        Element root = doc.getDocumentElement();
        int totalTests = 0;
        int totalFailures = 0;
        int totalErrors = 0;
        int totalSkipped = 0;
        double totalTime = 0.0;

        List<Element> testSuites = new ArrayList<>();

        if ("testsuites".equals(root.getTagName())) //$NON-NLS-1$
        {
            NodeList suiteNodes = root.getElementsByTagName("testsuite"); //$NON-NLS-1$
            for (int i = 0; i < suiteNodes.getLength(); i++)
            {
                testSuites.add((Element)suiteNodes.item(i));
            }
        }
        else if ("testsuite".equals(root.getTagName())) //$NON-NLS-1$
        {
            testSuites.add(root);
        }

        JsonArray failuresArray = new JsonArray();
        JsonArray allTestsArray = new JsonArray();

        for (Element suite : testSuites)
        {
            totalTests += getIntAttribute(suite, "tests", 0); //$NON-NLS-1$
            totalFailures += getIntAttribute(suite, "failures", 0); //$NON-NLS-1$
            totalErrors += getIntAttribute(suite, "errors", 0); //$NON-NLS-1$
            totalSkipped += getIntAttribute(suite, "skipped", 0); //$NON-NLS-1$
            totalTime += getDoubleAttribute(suite, "time", 0.0); //$NON-NLS-1$

            String suiteName = suite.getAttribute("name"); //$NON-NLS-1$

            NodeList testCases = suite.getElementsByTagName("testcase"); //$NON-NLS-1$
            for (int i = 0; i < testCases.getLength(); i++)
            {
                Element testCase = (Element)testCases.item(i);
                String testName = testCase.getAttribute("name"); //$NON-NLS-1$
                String className = testCase.getAttribute("classname"); //$NON-NLS-1$
                double testTime = getDoubleAttribute(testCase, "time", 0.0); //$NON-NLS-1$

                JsonObject testObj = new JsonObject();
                testObj.addProperty("name", testName); //$NON-NLS-1$
                testObj.addProperty("classname", className); //$NON-NLS-1$
                testObj.addProperty("suite", suiteName); //$NON-NLS-1$
                testObj.addProperty("time", testTime); //$NON-NLS-1$

                // Check for failure
                NodeList failures = testCase.getElementsByTagName("failure"); //$NON-NLS-1$
                if (failures.getLength() > 0)
                {
                    Element failure = (Element)failures.item(0);
                    String message = failure.getAttribute("message"); //$NON-NLS-1$
                    String details = failure.getTextContent();
                    testObj.addProperty("status", "failed"); //$NON-NLS-1$ //$NON-NLS-2$

                    JsonObject failureObj = new JsonObject();
                    failureObj.addProperty("name", testName); //$NON-NLS-1$
                    failureObj.addProperty("classname", className); //$NON-NLS-1$
                    failureObj.addProperty("message", message); //$NON-NLS-1$
                    if (details != null && !details.isEmpty())
                    {
                        failureObj.addProperty("details", details.trim()); //$NON-NLS-1$
                    }
                    failuresArray.add(failureObj);
                }
                // Check for error
                else
                {
                    NodeList errors = testCase.getElementsByTagName("error"); //$NON-NLS-1$
                    if (errors.getLength() > 0)
                    {
                        Element error = (Element)errors.item(0);
                        String message = error.getAttribute("message"); //$NON-NLS-1$
                        String details = error.getTextContent();
                        testObj.addProperty("status", "error"); //$NON-NLS-1$ //$NON-NLS-2$

                        JsonObject errorObj = new JsonObject();
                        errorObj.addProperty("name", testName); //$NON-NLS-1$
                        errorObj.addProperty("classname", className); //$NON-NLS-1$
                        errorObj.addProperty("message", message); //$NON-NLS-1$
                        if (details != null && !details.isEmpty())
                        {
                            errorObj.addProperty("details", details.trim()); //$NON-NLS-1$
                        }
                        failuresArray.add(errorObj);
                    }
                    // Check for skipped
                    else
                    {
                        NodeList skippedNodes = testCase.getElementsByTagName("skipped"); //$NON-NLS-1$
                        if (skippedNodes.getLength() > 0)
                        {
                            testObj.addProperty("status", "skipped"); //$NON-NLS-1$ //$NON-NLS-2$
                        }
                        else
                        {
                            testObj.addProperty("status", "passed"); //$NON-NLS-1$ //$NON-NLS-2$
                        }
                    }
                }

                allTestsArray.add(testObj);
            }
        }

        int passed = totalTests - totalFailures - totalErrors - totalSkipped;

        // Build summary
        JsonObject summary = new JsonObject();
        summary.addProperty("totalTests", totalTests); //$NON-NLS-1$
        summary.addProperty("passed", Math.max(0, passed)); //$NON-NLS-1$
        summary.addProperty("failed", totalFailures); //$NON-NLS-1$
        summary.addProperty("errors", totalErrors); //$NON-NLS-1$
        summary.addProperty("skipped", totalSkipped); //$NON-NLS-1$
        summary.addProperty("duration", String.format(java.util.Locale.US, "%.2fs", totalTime)); //$NON-NLS-1$ //$NON-NLS-2$
        summary.addProperty("allPassed", totalFailures == 0 && totalErrors == 0); //$NON-NLS-1$

        result.add("summary", summary); //$NON-NLS-1$
        result.add("failures", failuresArray); //$NON-NLS-1$
        result.add("tests", allTestsArray); //$NON-NLS-1$

        return result;
    }

    private static int getIntAttribute(Element element, String attrName, int defaultValue)
    {
        String value = element.getAttribute(attrName);
        if (value == null || value.isEmpty())
        {
            return defaultValue;
        }
        try
        {
            return Integer.parseInt(value);
        }
        catch (NumberFormatException e)
        {
            return defaultValue;
        }
    }

    private static double getDoubleAttribute(Element element, String attrName, double defaultValue)
    {
        String value = element.getAttribute(attrName);
        if (value == null || value.isEmpty())
        {
            return defaultValue;
        }
        try
        {
            return Double.parseDouble(value);
        }
        catch (NumberFormatException e)
        {
            return defaultValue;
        }
    }
}
